name: card
description: A game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.6+6

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.11.0
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  path_provider: ^2.0.2
  flutter_screenutil: ^5.9.0
  animated_card: ^2.0.0
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4
  country_flags: ^2.2.0
  flag: ^7.0.0
  country_picker: ^2.0.25
  intl: 0.18.1
  intl_translation: 0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/images/
    - assets/images/card_suit/
    - assets/images/background/
    - assets/images/items/recyclable/
    - assets/images/items/trashClassification02/
    - assets/images/items/trashClassification_0010/
    - assets/images/items/trashClassification_0011/
    - assets/images/items/trashClassification_0021/
    - assets/images/items/trashClassification_0022/
    - assets/images/items/trashClassification_0031/
    - assets/images/items/trashClassification_0032/
    - assets/images/items/trashClassification_0033/
    - assets/images/items/trashClassification_0041/
    - assets/images/items/trashClassification_0042/
    - assets/images/items/trashClassification_0043/
    #    - assets/images/items/trashClassification_0044/
    - assets/images/items/trashClassification_0050/
    - assets/images/items/trashClassification_0061/
    - assets/images/items/trashClassification_0062/
    - assets/images/items/trashClassification_0063/
    - assets/images/items/trashClassification_0064/
    - assets/images/items/trashClassification_0070/
    #    - assets/images/items/trashClassification_0080/
    #    - assets/images/items/trashClassification_0090/
    #    - assets/images/items/trashClassification_0100/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
